- name: Pause to wait Kube is ready
  ansible.builtin.pause:
    minutes: 1

- name: Create a the ingress
   kubernetes.core.k8s:
    kubeconfig: /tmp/kubeconfig-k3s
    resource_definition: "{{ lookup('file', 'traefik.yml') }}"
    state: present

- name: Create the app
   kubernetes.core.k8s:
    kubeconfig: /tmp/kubeconfig-k3s
    resource_definition: "{{ lookup('file', 'whoami.yml') }}"
    state: present
