- name: Pause to wait Kube is ready
  ansible.builtin.pause:
    minutes: 1

- name: Create a the ingress
  k8s:
    host: https://192.168.1.74:6443
    kubeconfig: /tmp/kubeconfig-k3s
    resource_definition: "{{ lookup('file', 'traefik.yml') }}"
    state: present

- name: Create the app
  k8s:
    host: https://192.168.1.74:6443
    kubeconfig: /tmp/kubeconfig-k3s
    resource_definition: "{{ lookup('file', 'whoami.yml') }}"
    state: present
